.TH VLOCK-NEW 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-new \- run a program on a new virtual console
.SH SYNOPSIS
.B vlock-new program [arguments...]
.SH DESCRIPTION
\fBvlock-all\fR is part of \fBvlock\fR, the Virtual Console locking program
for Linux.  It allocates and switches to a new virtual console and runs
\fIprogram\fR there.  After the \fIprogram\fR exits it switches back to the
previously active console.
.SH "EXIT CODES"
\fBvlock-new\fR exits 100 when called without arguments.  It prints an error
message and exits 111 if it has trouble switching to the new console.  It exits
127 if it has trouble running \fIprogram\fR.  If \fIprogram\fR is killed by a
signal it exits 128 plus the number of the signal.  Otherwise its exit code is
the same as that of \fIprogram\fR.
.SH "SEE ALSO"
.BR vlock (1),
.BR ioctl (2)
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
