.TH VLOCK-LOCKSWITCH 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-lockswitch \- disable virtual console switching
.SH SYNOPSIS
.B vlock-lockswitch
.SH DESCRIPTION
\fBvlock-lockswitch\fR is part of \fBvlock\fR, the Virtual Console locking
program for Linux.  It disables virtual console switching and is the
counterpart of \fBvlock-unlockswitch\fR.
.SH "SEE ALSO"
.BR vlock (1),
.BR vlock-unlockswitch (8),
.BR vlock-all (8),
.BR ioctl (2)
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
