.TH VLOCK-NOSYSRQ 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-nosysrq \- disable magic SysRQ keys and lock the console display
.SH SYNOPSIS
.B vlock-nosysrq
.SH DESCRIPTION
\fBvlock-nosysrq\fR is part of vlock(1), the Virtual Console locking program
for Linux.  It disables the magic SysRQ keys and runs vlock-all(8) or
vlock-new(8).  After the child program exits it reenables the SysRQ keys.
.SH "ENVIRONMENT VARIABLES"
.B VLOCK_NEW
.IP
If this environment variable is set \fBvlock-nosysrq\fR runs vlock-new(8).
Otherwise it runs vlock-all(8).
.SH "EXIT CODES"
\fBvlock-nosysrq\fR exits 111 after printing an error message if it has
disabling the SysRQ keys.  It exits 127 if it has trouble running vlock-all(8)
or vlock-new(8).  If vlock-all(8) or vlock-new(8) is killed by a signal it
exits 128 plus the number of the signal.  Otherwise its exit code is the same
as that of vlock-all(8) or vlock-new(8).
.SH "SEE ALSO"
.BR vlock (1),
.BR vlock-all (8),
.BR vlock-new (8),
.BR /usr/src/linux/Documentation/sysrq.txt
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
