.TH VLOCK-ALL 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-all \- lock console while preventing virtual console switching
.SH SYNOPSIS
.B vlock-all
.SH DESCRIPTION
\fBvlock-all\fR is part of vlock(1), the Virtual Console locking program for
Linux.  It disables console switching and runs vlock-current(8).  After
vlock-current(8) exits it reenables console switching.
.SH "EXIT CODES"
\fBvlock-all\fR exits 111 after printing an error message if it has trouble
disabling console switching.  It exits 127 if it has trouble running
vlock-current(8).  If vlock-current(8) is killed by a signal it exits 128 plus
the number of the signal.  Otherwise its exit code is that of vlock-current(8).
.SH "SEE ALSO"
.BR vlock (1),
.BR vlock-current (8),
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
