.TH VLOCK-NEW 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-new \- switch to a new console and lock the console display
.SH SYNOPSIS
.B vlock-new
.SH DESCRIPTION
\fBvlock-all\fR is part of vlock(1), the Virtual Console locking program for
Linux.  It allocates and switches to a new virtual console and runs
vlock-all(8) there.  After the vlock-all(8) exits it switches back to the
previously active console.
.SH "EXIT CODES"
\fBvlock-new\fR exits 111 after printing an error message if it has trouble
switching to the new console.  It exits 127 if it has trouble running
vlock-all(8).  If vlock-all(8) is killed by a signal it exits 128 plus the
number of the signal.  Otherwise its exit code is the that of vlock-all(8).
.SH "SEE ALSO"
.BR vlock (1),
.BR vlock-all (8),
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
