.TH VLOCK-NOSYSRQ 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-nosysrq \- disable magic SysRQ keys
.SH SYNOPSIS
.B vlock-nosysrq program [arguments...]
.SH DESCRIPTION
\fBvlock-nosysrq\fR is part of \fBvlock\fR, the Virtual Console locking program
for Linux.  It disables the magic SysRQ keys and runs \fIprogram\fR.  After the
\fIprogram\fR exits it reenables the SysRQ keys.
.SH "EXIT CODES"
\fBvlock-nosysrq\fR exits 100 when called without arguments.  It prints an
error message and exits 111 if it has disabling the SysRQ keys.  It exits 127
if it has trouble running \fIprogram\fR.  If \fIprogram\fR is killed by a
signal it exits 128 plus the number of the signal.  Otherwise its exit code is
the same as that of \fIprogram\fR.
.SH "SEE ALSO"
.BR vlock (1),
.BR sysctl (8),
.BR /usr/src/linux/Documentation/sysrq.txt
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
