.TH VLOCK-UNLOCKSWITCH 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-unlockswitch \- enable virtual console switching
.SH SYNOPSIS
.B vlock-unlockswitch
.SH DESCRIPTION
\fBvlock-unlockswitch\fR is part of \fBvlock\fR, the Virtual Console locking
program for Linux.  It enables console switching.  It is meant primarily as a
rescue tool should it be necessary to kill \fBvlock-grab\fR, leaving the
virtual console switching disabled.
.SH "SEE ALSO"
.BR vlock (1),
.BR vlock-grab (8),
.BR vlock-lockswitch (8),
.BR ioctl (2)
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
