.TH VLOCK-CURRENT 8 "28 July 2007" "Linux" "Linux Programmer's Manual"
.SH NAME
vlock-current \- lock current virtual console
.SH SYNOPSIS
.B vlock-current
.SH DESCRIPTION
\fBvlock-current\fR is part of vlock(1), the Virtual Console locking program
for Linux.  Once started it only exits if correct authentification data (either
the current user's or root's) is received.  Authentification can be done
against PAM or shadow, determined at compile time.
.SH "ENVIRONMENT VARIABLES"
.B USER
.IP
When \fBvlock-current\fR is run as root (uid 0) and this environment variable is
set \fBvlock-current\fR works the same as if it was run by that user.
.PP
.B VLOCK_MESSAGE
.IP
When this environment variable is set \fBvlock-current\fR prints its contents
before each password prompt.
.PP
.B VLOCK_PROMPT_TIMEOUT
.IP
Set this variable to specify the amount of time (in seconds) you will have to
enter your password at the password prompt.  \fBWarning\fR: If this value is too
low, you will have trouble unlocking your machine.
.SH "EXIT CODES"
\fBvlock-current\fR exits 111 when the username can not be determined.
.SH SIGNALS
SIGINT, SIGQUIT, and SIGTSTP are ignored ignored.  If \fBvlock-current\fR
is killed by any other signal the terminal is not restored.
.SH "SEE ALSO"
.BR vlock (1)
.SH AUTHORS
Frank Benkstein <frank-vlock@benkstein.net>
