.TH VLOCK 1 "16 May 1996" "Linux User's Manual"
.SH NAME
vlock \- Virtual Console lock program
.SH SYNOPSIS
.B vlock
.PP
.B vlock [ -a,--all ] [ -c,--current ] [ -h,--help ] [ -v,--version ]
.SH DESCRIPTION
.B vlock
is a program to lock one or more sessions on the Linux console.  This is
especially useful for Linux machines which have multiple users with access
to the console.  One user may lock his or her session(s) while still allowing
other users to use the system on other virtual consoles.  If desired, the
entire console may be locked and virtual console switching disabled.
.PP
By default, only the current VC (virtual console) is locked.  With the
\fB-a,-all\fR option all VCs are locked.  The locked VCs cannot be unlocked
without the invoker's password or the root password.  The root password will
always be able to unlock any or all sessions.  And, for the paranoid,
vlock makes it a trying experience for those attempting to guess the
password, so unauthorized access to session(s) is highly unlikely.
.PP
Please note that it is entirely possible to completely lock yourself out of
the console with the \fB-a,--all\fR option if you cannot remember your
password!  Unless you are able to kill vlock by logging in remotely via a
serial terminal or network, a hard reset is the only method of ``unlocking''
the display.
.PP
.B vlock
tries to allow the root password to unlock sessions.  This only works if
.B vlock
has sufficient permissions to read the crypted password for root.  This
is not the case on systems with shadow passwords and PAM.  In that case,
when it prompts for the root password, it will always fail, even if you
type in the right password.  While this looks like a bug, it isn't, it
is just a natural limitation of "negative privileges" on shadow password
systems.
.PP
When locking the entire console display it is still possible to kill vlock
using the Secure Access Key (SAK) or other commands that are available
through the sysrq mechanism when that was enabled.  When the \fB-s,--disable-sysrq\fR
is given the sysrq mechanism is disabled while vlock is running and reenabled
on exit.  See /usr/src/linux/Documentation/sysrq.txt for more details.
.PP
\fBvlock\fR works for console sessions primarily.  However, there is
support for trying to lock non-console sessions as well, but that
support has not been well tested.
.SH OPTIONS
.B -a,--all
.IP
Lock all console sessions and disable VC switching.
.PP
.B -s,--disable-sysrq
.IP
Disable sysrq while consoles are locked. Does not have effect unless
the \fB-a,--all\fR option is also specified.
.PP
.B -c,--current
.IP
Lock the current session (this is the default).
.PP
.B -h,--help
.IP
Print a brief help message.
.PP
.B -v,--version
.IP
Print the version number of \fBvlock\fR.
.PP
.SH AUTHOR
Michael K. Johnson <johnsonm@redhat.com>
